### ISSUE TITLE
Draft and published mode for Moments and Strategies

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#10]
Saving as a draft does not publish the trigger/strategy to the user's allies. On the other had, publishing does.

**Comment by julianguyen** [comment]
How's this going @damiong28?

**Comment by damiong28** [comment]
Still working on it!

**Comment by julianguyen** [comment]
How's this going @damiong28? :)

**Comment by cartothemax** [comment]
@damiong28 would it be alright if I picked up this issue?  Thanks!

**Comment by jnamster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Draft and published mode for moments and strategies](https://trello.com/c/jrE3hU0h/25-3-draft-and-published-mode-for-moments-and-strategies)

**Comment by alvarocasadoc** [comment]
I've been working a bit on this. Here's what I think could work well and some suggestions and notes about it's implementation:

## Expected behaviour
### Adding/editing a moment/strategy
- When a user **adds** a moment/strategy he/she can click on one of these **submit buttons**
![publishing buttons](https://user-images.githubusercontent.com/7248474/31291725-0657f718-aad1-11e7-921f-5351427b4b52.png)
- If the user selects **Publish** the moment/strategy will become available as it is done now.
- If the user selects **Save as draft** only he/she will be able to view its info.
- When a user **edits** a moment/strategy she/he can decide wether to publish it or keep it as a draft even if it was already published. 
![publishing buttons 2](https://user-images.githubusercontent.com/7248474/31292163-a0e61cd2-aad2-11e7-92d9-f382de003a6d.png)

### Displaying moments/strategies
- **Every user can view all his/hers moments/strategies.**
- When a moment/strategy is saved as draft **a small badge** is displayed next to the created/edited info in the index:
![draft badge](https://user-images.githubusercontent.com/7248474/31291828-6cd55134-aad1-11e7-8355-38febe37766b.png)
- This badge is also displayed when a moment/strategy is displayed via show.
- **When a user visits other user's profile** he won't be able to view his/hers moments/stories that are saved as drafts.

## Current implementation
- Added a `published_at` field to the Moment/Strategy **models** and DB schema.
- Modified moment/strategy **forms** to include multiple submit buttons.
- Modified moment/strategy **controllers** to respond to the different submit buttons commit types (publish/save as draft/unpublish).
- Modified `get_stories` in `application_controller.rb` to filter other users' stories (only displaying those that are already published).

## Next
- **Make sure that a user can't access another user's stories if they are not published** (we don't want only filter them in the view). This could be implemented in `hide_page?` in `application_controller.rb`.
- Writing the required model, controller and feature **tests**.
- Update `application_controller_spec` to test the `get_stories` and `hide_page?` methods.

## Questions and suggestions
- **Should the stats on a user's profile page stop considering draft moments/strategies?** This means no moment/strategy nor dependent associations (moods/categories/strategies) should be counted.
- Is there any other desired behavior that should be implemented? 
- Is there anything that should be changed in the described implementation?
- Any UX notes are appreciated!

**Comment by julianguyen** [comment]
Wow @alvarocasadoc this is looking fantastic, really great attention to detail 💯 

I like the different states you put on the button. If it helps you keep organized, feel free to create separate issues for each of the different tasks you have to do and put them all into a [project](https://github.com/julianguyen/ifme/projects).

Along with `When a user visits other user's profile he won't be able to view his/hers moments/stories that are saved as drafts.` which is a great idea, I think a user should be able to view their own profile with draft posts.

Great questions:
* Yeah that stats should just include published posts.
* I think we can have the same draft indicator you have in the story card in the post itself beside the Created: section.

Anyone else feel free to chime in! 

Thanks a million for this, I'm excited to see this feature finally roll out!

**Comment by nshki** [comment]
This is awesome @alvarocasadoc! Only feedback I have at the moment is in regards to the UI controlling publish/draft state.

What if we utilize a checkbox of sorts that makes it visually clear what state a moment/strategy will be in once the form is submitted rather than having multiple buttons that send different params back to the server? So, for example:

![publish-draft](https://user-images.githubusercontent.com/1121087/31311316-8f397fec-ab77-11e7-9ccb-970930e7cdc0.png)

This way, the user only has to think about one submit button, and it will be clear to them whether or not the moment/strategy will be published or be saved as a draft on submit.

**Comment by alvarocasadoc** [comment]
I think that's a great idea! What about something like this?
![](https://user-images.githubusercontent.com/7248474/31316534-b217e0fe-ac2f-11e7-9c31-582746bbac18.png)
![](https://user-images.githubusercontent.com/7248474/31316539-c7c6468e-ac2f-11e7-8de3-38fe81bc2552.png)

![demo](https://user-images.githubusercontent.com/7248474/31316455-1f68cf44-ac2e-11e7-8c09-d168e99a7d0a.gif)

**Comment by alvarocasadoc** [comment]
This is what a user can see in his/her own profile:
![ownprofile](https://user-images.githubusercontent.com/7248474/31316580-877a2a68-ac30-11e7-9122-a779fface9f6.png)

And this is what another user can see when he/she visits his ally profile:
![othersprofile](https://user-images.githubusercontent.com/7248474/31316585-9aa332ba-ac30-11e7-82d0-d457ece9c35b.png)

**Comment by nshki** [comment]
Looking good! 💯 

Will be revisiting design with #691 but I think what you have is great prior to the redesign!
