### ISSUE TITLE
Broken unit test: ErrorsController

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#115]
![screen shot 2016-05-02 at 7 48 16 pm](https://cloud.githubusercontent.com/assets/3010728/14973632/0c02a992-109f-11e6-8192-09e97ef19168.png)

All the unit tests in ErrorsControllerSpec are broken :(

Hey @IuliiaKot, do you think you can quickly look into this? :)

**Comment by siyegen** [comment]
Hey @julianguyen I ran into this issue while looking at #116 (since it just seems rude to submit a PR with broken tests) and believe I found the issue.

the ```.have_http_status``` matcher looks to be present in rspec-rails 3.4, but the Gemfile does not specify a version so I ended up getting rspec-rails 2.99

This can be fixed by upping the version to get the macher, or by changing ```expect(response).to have_http_status(404)``` to ```response.code.should eq("404")```

I wasn't sure which you'd prefer, I'd lean towards upgrading since this is a Rails 4 project and that's the target for the new rspec-rails, but I haven't been a rails dev in a while and don't want to assume. Let me know and I can do either and submit a PR.

**Comment by julianguyen** [comment]
@siyegen Excellent find! I think upgrading would be better then! Looking forward to seeing the PR! Thanks :)

**Comment by siyegen** [comment]
Sure, here it is #117

**Comment by julianguyen** [comment]
💯
