### ISSUE TITLE
Adding ally shows blank confirmation page

### ISSUE THREAD

**Issue by finitem** [julianguyen/ifme#174]
Browser: Firefox 46.0.1
OS: Windows 10
Date: 2016-05-28

![ally_broke_source](https://cloud.githubusercontent.com/assets/8795569/15628193/27ac4250-24c9-11e6-8513-4013e9671afe.PNG)

Issue: After adding an ally, the user is redirected to a blank page. The ally is successfully added, but the user's experience is interrupted.

Reproduction steps:
1. Sign into if-me
2. Go the the allies section
3. Search for ally
4. Select "add to allies" on ally you'd like to add
5. !Be brought to /allies/add?ally_id=<id>, which is displaying an empty page
6. navigate to /allies and that ally is succesfully added

**Comment by merrillogic** [comment]
Dev note: There is also a 500 internal server error.

Post params:
ally_id 10

**Comment by julianguyen** [comment]
Are you still encountering this issue? O.o

**Comment by finitem** [comment]
Yup! Just tried again, still shows me the blank page, and presumably the server errored. It would be about 13:27:40 UTC, if you feel like digging through the logs of the active server : )

**Comment by julianguyen** [comment]
@finitem Hey can you adding me again? I added an add-on on Heroku to save all the logs not just the last 1500 lines... lol 

When adding allies, you are supposed to be redirected to the previous page you were on (but refreshed) i.e.

```
respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
```

Do you have some kind of setting your browser that disables that or clears the cache? O.o

**Comment by finitem** [comment]
Tried again at roughly 14:30:45 UTC. I don't think I have settings any different from the default - I also tried it in Brave 0.10.0 just now (14:32 UTC) and that had the same issue. It does show this error in Firebug if I persist the logs:

The connection to wss://ws.pusherapp.com/app/5e89ca103f7429c1e78d?protocol=7&client=js&version=3.0.0&flash=false was interrupted while the page was loading.
		
...ebSocket)},getSocket:function(a){return new (window.WebSocket||window.MozWebSock...
pusher.min.js (line 61, col 129)

**Comment by julianguyen** [comment]
So the error has nothing to do with redirect. It has to do with SMTP, so when you add me I get emailed.

```
May 30 09:33:33 ifme app/web.1:  Sent mail to tojulianguyen@gmail.com (3.3ms) 
May 30 09:33:33 ifme app/web.1:  Completed 500 Internal Server Error in 28ms (ActiveRecord: 8.9ms) 
May 30 09:33:33 ifme app/web.1:  ArgumentError (SMTP-AUTH requested but missing secret phrase): 
May 30 09:33:33 ifme app/web.1:    app/controllers/allies_controller.rb:51:in `add' 
```

**Comment by julianguyen** [comment]
Wooow the issue was that I spelled password wrong in the SMTP settings LMAO.

**Comment by julianguyen** [comment]
@finitem Hey! Can you test again? (Hopefully the last time?)

**Comment by finitem** [comment]
It works! Woohoo!

Aren't typo bugs just the best?

**Comment by julianguyen** [comment]
Yassss~ thank you Jonathan :)

OMG there was no typo in master, but there were in production. My fault completely >.<

**Comment by dleve123** [comment]
Hey @julianguyen - happy you were able to solve this! Was there a typo in the the codebase somewhere for the word "password" (I don't see a commit that fixes such a typo, so I don't think there was a typo there, but just double checking), or was there a typo within the Heroku ENV configuration itself?

If the latter, there are some techniques that help reveal typo errors on application boot-time (usually when deploying to Heroku), rather than execution-time (when the mailer is actually being called).

In the app I work on (which is deployed on a platform similar to Heroku), we use Rails' built-in `config/secrets.yml` with [Dotenv](https://github.com/bkeepers/dotenv), and liberal use of [`ENV#fetch`](http://ruby-doc.org/core-1.9.3/ENV.html#method-c-fetch) to attempt to solve this problem. https://github.com/julianguyen/ifme/commit/3cfc18462c8a69f953a1d46d10ae4d55594dbe2f seems to start getting in this direction by implementing Figaro, but I'm not too familiar with that approach.

Configuration management is tricky and often not too exciting; regardless, I hope this helps!

**Comment by julianguyen** [comment]
@dleve123 The typo was within the Heroku ENV configuration >.<
We're using Figaro! Thanks for the advice :)
