### ISSUE TITLE
Fresh comments on moments display time in UTC

### ISSUE THREAD

**Issue by finitem** [julianguyen/ifme#178]
Browser: Firefox 46.0.1
OS: Windows 10
Date: 2016-05-28

![moment_comment_utc](https://cloud.githubusercontent.com/assets/8795569/15628574/2e280ac0-24d2-11e6-9896-1281280769f8.PNG)

Issue: When you make a new comment on a moment, the time is displayed in UTC until you refresh the page.

Repro steps:
1. Select a moment
2. Comment
3. !Observe the time in UTC, instead of your local time.

**Comment by julianguyen** [comment]
FYI to anyone taking a look at this bug, we are using a gem called local_time to get the user's timezone.

**Comment by julianguyen** [comment]
Looks like the Time.zone is being correctly and it's an issue with the local_time gem...

**Comment by starbelly** [comment]
@julianguyen and @finitem the problem is local_time needs a UTC offset as part of the date time string. There's a few ways to handle this. One is with ActiveSupport, as long as Time.zone is set correctly on a per user basis and only Time.zone is used for dealing with Time, then all should be well. Going that route, local_time is obsoleted. However,  I would prefer not be married to active record and store the users utc offset in their table, then you can simply concat the date time field with the users UTC offset and all should be well. 

 This looks like a good article on the subject: 
http://danilenko.org/2012/7/6/rails_timezones/

**Comment by julianguyen** [comment]
@starbelly Currently we are setting Time.zone using the timezone specified by the user's browser

https://github.com/julianguyen/ifme/blob/master/app/controllers/application_controller.rb#L27

Thoughts on this method?

**Comment by starbelly** [comment]
@julianguyen Wierdness. That was not in the fork I had just cloned last night, perhaps I was behind... 

 Ok, see where the problem is. If you post a comment, you will immediately see the time in UTC, this is normal behavior per local_time. If you wait and wait and wait the time will eventually get converted to local time before your very eyes. So, the question now is: Why the delay?

**Comment by julianguyen** [comment]
@starbelly What you're describing seems to be happening.... but I'm confused why during new page loads or reloads it gets converted right away... Do you think we should continue using this gem or write our own helpers for formatting time?

**Comment by starbelly** [comment]
I think we should use our own helpers. We should discuss the pros and cons of letting the client handle this vs. server side as well. The pros using the client to convert the time data is pushing the load on to the client. However, the cons I think outweigh the pros in that there's way more that can wrong as we're seeing. I think the load increase caused by such operations server side are negligible, and I vote to ditch the client side code for local time rendering.

**Comment by julianguyen** [comment]
Yeah I do not like having to rely on a gem, especially when there are clear bugs. I'm going to do more digging on this and see if I can fix it without having to write new helpers. If not, I'll start writing helpers.

**Comment by julianguyen** [comment]
I will be refactoring this code more so that we are only keeping what we need.
