### ISSUE TITLE
Possibly change license

### ISSUE THREAD

**Issue by starbelly** [julianguyen/ifme#201]
Not demanding a change here. Just wondering why use the Apache license over the GPL?

**Comment by julianguyen** [comment]
I originally chose Apache because it had the fewest limitations but still enforced licence and copyright notice, and state changes. But I think as this project grows we should probably choose a licence with more conditions, which version of GPL are you leaning more towards? GNU AGPLv3 looks the strongest.

**Comment by starbelly** [comment]
GNU AGPL v3 looks good to me 👍

**Comment by julianguyen** [comment]
https://github.com/julianguyen/ifme/commit/a4e1ea368280442bfe11f631e880dc35f652571c
