### ISSUE TITLE
Accessibility Issue - Multiple h1 tags in footer

### ISSUE THREAD

**Issue by johnfrenchxyz** [julianguyen/ifme#224]
I've noticed that, in the footer, the "if me" and "connect" sections are both `<h1>` tags with additional styles applied to them. Having more than one `<h1>` tag on a page can make a non-css view difficult to understand, or cause a screen reader encounter unpredictable behavior.
 [
You can read more about best-practices here.](http://webaim.org/techniques/semanticstructure/#maincontent)

Locally, I have converted the `<h1>` tags to `<span>` tags and updated the scss (but have not yet compiled it to CSS, as I am slightly new to the rails file structure - is this done automatically with the asset pipeline?).  

When testing this fix in Chrome's developer tools - fixes the problem without altering the style of the footer. I have cloned the repo locally and created a new branch for these changes, but it appears as though I need to be added as a contributor before I can push the changes to my branch and submit a pull request.

**Comment by stellacotton** [comment]
Hey John, an easy way to make a PR if you aren't a contributor is to fork the app to your own repo. Github has some instructions here: https://help.github.com/articles/fork-a-repo/

Since you've already pulled the repo down, after you fork the repo you can skip the steps in the instructions in Step 3.1 - 3.4 about pulling down the clone and go straight to Step 3.5 where it talks about setting up the remote.

Hope this is helpful!

**Comment by johnfrenchxyz** [comment]
@stellacotton thanks! I'll look into that now.

**Comment by johnfrenchxyz** [comment]
Just submitted a PR #225
