### ISSUE TITLE
Developing without SMTP configuration

### ISSUE THREAD

**Issue by janz93** [julianguyen/ifme#244]
Hey 
I chose not to setup my SMTP email which makes no email communication possible.
As I was trying to invite an ally the page returned a 500 error.
Would it make sense to handle the case where there is no email configuration? 
Obviously not everything would work without email but most things would.

```
Completed 500 Internal Server Error in 921ms (ActiveRecord: 2.9ms)

Net::SMTPAuthenticationError (535-5.7.8 Username and Password not accepted. Learn more at
):
  app/controllers/users/invitations_controller.rb:5:in `create'
  app/controllers/application_controller.rb:29:in `block in with_timezone'
  app/controllers/application_controller.rb:29:in `with_timezone'
```

**Comment by julianguyen** [comment]
That's a great point @janz93! How do you think we should handle this? Skip SMTP authentication if it doesn't exist and it's in development mode?

**Comment by stellacotton** [comment]
@julianguyen I think this is a bug and related to https://github.com/julianguyen/ifme/issues/220. I hadn't had a chance to look into it before now, but I think it's an issue with "false" as a string in the key/value pairs. I think I was trying to round hole/square peg our use of Figaro so that we could use it to manage both secrets and configuration booleans (specifically in `ifme/config/environments/development.rb` where we turn the mailer on or off). Right now its returning a string `"false"`, which is obviously not the same as the boolean `false` (whoops!).

Offhand, I think the two options are:
1. Using `ENV.key?("SEND_EMAIL")` in `ifme/config/environments/development.rb` to return a boolean instead of returning a string `"false"`. The weird thing about this is that the configuration in `ifme/config/application.example.yml` would look like:

 `RAISE_DELIVERY_ERRORS: "yes_please"` (or whatever, it wouldn't matter what the value actually is because anything other than nil is true) 
or
 `RAISE_DELIVERY_ERRORS: nil`

instead of true & false. Which isn't a huge deal to explain in a comment, but may be a little weird.

2. Adding `ifme/config/environments/development.rb` to gitignore and making a `ifme/config/environments/development.rb.example` where we'd still need a comment explaining that you need to turn the flag on if you want to send email.

**Comment by julianguyen** [comment]
I like the latter option @stellacotton because it is the most minimal, but would the first option be better for new contributors? Thoughts @janz93?

**Comment by janz93** [comment]
I think the first option would be better since it wouldn't mean extra work for someone to set up the project.
Also maybe `ENV.fetch('SEND_EMAIL', 'any default value')` could be an option if it would be better to be in control of what a default value should be.

**Comment by julianguyen** [comment]
Good point @janz93! Would you like to set this up?

**Comment by stellacotton** [comment]
@janz93 I'm not sure `ENV.fetch` will address the underlying issue where Figaro only allows strings or nil as configuration values in the `application.yml`. Rails needs a boolean (not a string value of `"true"` or `"false"`) to turn off sending email, which I think we can only get from `ENV.key?("SEND_EMAIL")`.

**Comment by stellacotton** [comment]
(Also this is unrelated, but if anyone is curious to look under the hood of one of our dependencies, the Figaro code is really easy to read. The place where it handles configuration values is here https://github.com/laserlemon/figaro/blob/5191084e16cf5cd5c2cc8a98df9071dbac9b4cba/lib/figaro/application.rb on line 72.)

**Comment by janz93** [comment]
Okay sounds great.
Till next Wednessday I will be busy but then I will try to take a look and start working on a PR.

**Comment by julianguyen** [comment]
@janz93 Hey what's the status on this? :)

**Comment by janz93** [comment]
Hey Sorry for the delay.
I'm have been working on a bigger projekt the last months and haven't had time to take a look at anything yet.
I'm still willing to develop the improvement but I won't be able to do so this month.

**Comment by logeshmallow** [comment]
@julianguyen: If I understand correctly, you do not want to use your SMTP credentials in development but you get an error during invite. If there is no issue with the mails being shown in browser on invite without the smtp credentials, then I can add letter opener gem and send a pull request to you. Please let me know if this is right and I shall send you the Pull Request soon.

**Comment by julianguyen** [comment]
@janz93 Any updates on this?
@logeshmallow Locally, we don't want SMTP credentials to be mandatory. So we should be able to "fail gracefully" if not credentials are provided in the development environment. Could you clarify what the letter opener gem does?

Also! Please email join.ifme@gmail.com so we can add you to your Slack :)

**Comment by logeshmallow** [comment]
@julianguyen: The letter opener gem is actually to preview email in the default browser instead of sending it actually. By adding the gem, we can set 

config.action_mailer.delivery_method = :letter_opener

and now all the mails will be opened in browser instead of actually sending it to whom ever we send and we could also be able to test if the mail functionality is also working properly and since we set this, we wont be requiring the smtp credentials.

Reference:
https://github.com/ryanb/letter_opener

**Comment by julianguyen** [comment]
@logeshmallow Ooh that's handy. Will we have to change the mailer test specs if we use this gem?

**Comment by logeshmallow** [comment]
@julianguyen: No, we don't need to change the mailer test spec on using this.

**Comment by julianguyen** [comment]
Sweet! Sounds like a good enhancement then @logeshmallow. Do you want to work on this?

**Comment by logeshmallow** [comment]
@julianguyen Yes, definitely. I can do this and send you a pull request.

**Comment by logeshmallow** [comment]
@julianguyen I have added letter opener and tested it and sent you a pull request.

**Comment by andrezacm** [comment]
Hey, I noticed this enhancement was merged, but in the readme is still mandatory to configure smtp, and this issue is open. I tried skip smtp configuration and is working, so what you guys think to change the readme file to not confuse anyone?

**Comment by julianguyen** [comment]
@andrezacm Yeah feel free to update the docs! Thanks for pointing this out!

**Comment by andrezacm** [comment]
thanks to answer so quickly :) 
just sent a PR
