### ISSUE TITLE
Internationalize app for Spanish and future languages

### ISSUE THREAD

**Issue by julianguyen** [julianguyen/ifme#251]
![wsc_opensourcehours](https://cloud.githubusercontent.com/assets/3010728/24170861/8127b1ba-0e3f-11e7-8b0b-dcfe8661b3b9.png)

The wonderful [Zoraida](https://twitter.com/ZoraidaEMedrano) from [Brown Sisters Speak](http://www.brownsistersspeak.org/) offered to help out with Spanish translations! 

We need someone to help out with make ensuring all the text in the app is in `en.yml`, coordinating with her to create an `es.yml`, and setting up a language toggle in the footer of the app.

**Comment by sienatime** [comment]
I'd like to help with this :)

**Comment by julianguyen** [comment]
Ooh that would great @sienatime! I'll introduce you two on Slack :)

**Comment by julianguyen** [comment]
@sienatime and anyone else who wants to help out:
- We should start putting all of the English text that isn't in en.yml there
- Sync with Zoraida give her that file to do the Spanish translations on
- While we're doing that perhaps work on the actual mechanism to switch between languages on the site

**Comment by sienatime** [comment]
Tasks:

- [ ] Standardize pluralization to use en.yml instead of ternary operated statements or `.pluralize`

  Example:
    Don't:
      `t('member').pluralize(members.count)`
      `members.count == 1 ? t('member') : t('members')`
    
    Do:
```
       (en.yml)
       member:
        one: Member
        other: Members
```

- [ ] Organize en.yml according to concepts and not controller/action/view where it makes sense in order to prevent string duplication
- [x] Fully qualify i18n keys (e.g. prefer `t('members.index.title')` instead of `t('.title')` where the controller is `members` and the action is `index`). This helps with clarify and also identifying strings that are not used.
- [ ] Identify and refactor uses of string concatenation to be more i18n-friendly
- [ ] Make sure all content is in the en.yml file
- [ ] Use `_html` instead of `raw`, e.g. if your string has markup in it (which should be minimal), the key should end in `_html` instead of you calling `raw` (which is unsafe) from the view
- [ ] For more best practices, see http://thepugautomatic.com/2012/07/rails-i18n-tips/

After above is completed:
- [ ] Send en.yml to Zoraida for translation into Spanish (es.yml)
- [ ] Implement language toggle on the site
- [ ] Manually test the app in Spanish

**Comment by arbonap** [comment]
hola todxs!
I'd also love to help with i18n tasks. I also speak Spanish, so I could help with translating as well. Let me know where I can best help. :)

**Comment by julianguyen** [comment]
This would be awesome @arbonap!  💯💯💯 Can you email us at join.ifme@gmail.com so we can add you to our Slack? :)

**Comment by pixelead0** [comment]
Hi, 
Where is the yml file to translate?

**Comment by julianguyen** [comment]
Hey @pixelead0! We're doing the translations in a Google doc currently then moving it over to yml, so that it's easier for the non-technical folks to look at. Can you send us an email at join.ifme@gmail.com so we can add you to the Slack?

**Comment by julianguyen** [comment]
Wrapping up this project and working on the toggle https://github.com/julianguyen/ifme/tree/i18n-ui-toggle
