### ISSUE TITLE
Creating a PR caused a Travis CI Failure

### ISSUE THREAD

**Issue by jfriestedt** [julianguyen/ifme#264]
Build log is [here](https://travis-ci.org/julianguyen/ifme/builds/155800373)

Error occurs on ln: 411, at the beginning of Jasmine tests. Error reads "Phantomjs does not appear to be installed in /home/travis/.phantomjs/2.1.1/x86_64-linux/bin/phantomjs, installing!"

PhantomJS appears to be installed locally for me as I am able to successfully run the Jasmine testing suite. Apologies if this is an oversight on my part in setup!

**Comment by julianguyen** [comment]
@jfriestedt This is a really weird bug. I find that rebuilding the test fixes the issue. But I don't know how else to fix it permanently so that we don't encounter it again.

**Comment by julianguyen** [comment]
Any ideas @siena or @starbelly?

**Comment by starbelly** [comment]
@julianguyen @jfriestedt 

 Right, so what's happening is the mirror where phantomjs is sitting is not responding to the request for the download of the bzip file. It's probably because a lot of builds from your container on travis-ci have it the mirror and the mirror is trying to protect itself from a DoS attack. At least, this was the case when it happened to me. 

 The real problem is the phantom-js gem trying to auto-install phantomjs. The phantomjs-gem looks for a version of phantomjs that matches what's listed in the phantom-js gem file. If it doesn't find that, then it downloads and installs. Obviously this can present problems : ) 

 I just disabled the auto-install of phantomjs in jasmine_helper (per docs at https://github.com/jasmine/jasmine-gem ) and  did a PR which should resolve this issue. 

Build log is here: https://travis-ci.org/starbelly/ifme/jobs/156395794

 You can see now it doesn't even try to install phantomjs, which is what we want since travis already has phantomjs pre-installed.

**Comment by julianguyen** [comment]
Thanks so much for this @starbelly ^_^
