### ISSUE TITLE
Add tests for notifications.js

### ISSUE THREAD

**Issue by zachariast** [julianguyen/ifme#308]
Add some tests for notifications.js

**Comment by julianguyen** [comment]
Noticed that the clear button doesn't get removed when you initially open the notifications modal, but it does when you click the clear button.

![screen shot 2016-10-07 at 1 01 54 am](https://cloud.githubusercontent.com/assets/3010728/19182757/c770a250-8c29-11e6-9af1-34bec49597e5.png)

**Comment by zachariast** [comment]
@julianguyen i'll check it now

**Comment by zachariast** [comment]
@julianguyen i can't see the problem. When i open notification modal i see this.
![screen shot 2016-10-07 at 11 57 53 am 1](https://cloud.githubusercontent.com/assets/8640923/19184365/6a0202e2-8c85-11e6-9103-922f379b5f52.png)

**Comment by julianguyen** [comment]
@zachariast 
Reproduction steps (locally and on prod):
- Log on
- Go to sub-navigation bar and click "Notifications"
- Modal opens, clear button still present

I think what we want to do is call `$('#notifications #clear_notifcations').hide();` after the AJAX request which fetches the notifications from the server (if it is empty).

**Comment by tcdowney** [comment]
@zachariast @julianguyen 

I was working on adding a Jasmine spec to cover my change on #320 and I noticed a couple of issues.

There looks like there is a syntax error [here on line 43](https://github.com/julianguyen/ifme/blob/master/spec/javascripts/notificationsSpec.js#L43) that's preventing Jasmine from loading this file and running these specs.

Also, would you be opposed to introducing https://github.com/velesin/jasmine-jquery to the project so that we can use test fixtures?  That would also let us use things like the `toBeHidden()` matcher.

**Comment by julianguyen** [comment]
Thanks for pointing this out @tcdowney. Can you fix that syntax error @zachariast please? :)

Not opposed to using jasmine-jquery. We definitely need test fixtures.

**Comment by nchambe2** [comment]
Yes, I have the commit. I got a new computer, and haven't been able to get the project up and running locally again. I'm going to try again, and hope to have the commit pushed before the end of the week.

**Comment by zachariast** [comment]
@julianguyen yes i'll do it. :)
