### ISSUE TITLE
`font-weight: 100` on subtitles doesn't look very nice/readable

### ISSUE THREAD

**Issue by pederjohnsen** [julianguyen/ifme#550]
Not sure if it's the same on other operating systems but on Windows 10 (in Chrome at least) the subtitles on the `sign in` and `join` pages are not very readable imo.

![http://i.imgur.com/xQ9lhS5.png?1](http://i.imgur.com/xQ9lhS5.png?1)

**Comment by julianguyen** [comment]
This is a really good point, @baohouse recently worked on updating some font stuff -- have any thoughts on this? :D

**Comment by baohouse** [comment]
Weight 100 is very thin... it has always been used for the subtitle, before and after #526. But text rendering differs across browsers and OS platforms, unfortunately. On OSX, it looks fine. But on Windows, it looks like it's about to fade into the air (as in the screenshot above).

We can bump up the weight to 200 (or even 300), but do we want it applied only to Windows platforms—in which case we'd have to use platform-specific CSS, and that can open up a can of worms—or should we make it universally 200/300? I prefer the latter, to keep things simple.

To better test, do we have specifications on supported browsers and OS? I have access to virtual instances of browser-OS combinations so I can generate screenshots, but it'd be good to know what we're supporting so that we can determine if the changes should be merged in or not.

If we don't have a browser support list, I can take a stab at drafting up one.

**Comment by julianguyen** [comment]
I'm cool with bumping up all instances of 100 to 200. 

We don't have any specs for browser support. That would be great to have, feel free to add a new page to the repo Wiki.

- Browsers: Chrome, Safari, Firefox, IE (> v.10), Edge, Opera
- Devices: Mac, Linux, Windows, iOS, Android (> v.4.0.0)

In general, we want people to do cross-browser and device testing :D https://www.browserling.com/ is an example of a free tool.

**Comment by pederjohnsen** [comment]
200 already looks way better on both windows and linux so should be good enough imo :+1:

**Comment by baohouse** [comment]
[SignUpScreenshots-7ab371c.zip](https://github.com/julianguyen/ifme/files/1243722/SignUpScreenshots-7ab371c.zip)

Screenshot tests on various browsers. On Firefox for Windows, it still looks kinda awful. There are other visual problems unrelated to the font-weight, so I'll file them as separate bugs.

**Comment by baohouse** [comment]
![bs_win10_firefox_55 0](https://user-images.githubusercontent.com/4228012/29593025-ae73a610-875c-11e7-936d-d43f6a6f35b9.jpg)

Retested Firefox on Windows. It seems to be related to using the virtualized OS. From what I can read on their [support forum](https://support.mozilla.org/en-US/questions/1115938), if hardware acceleration is turned off, then it will render in GDI mode (giving you that ugly jagged look). But you can override the settings in about:config, so I tried that, and it looks fine.

I'm going to close this issue since the font-weight problem seems to pass all the common browsers/devices.
