### ISSUE TITLE
Add Babel to support ES6

### ISSUE THREAD

**Issue by baohouse** [julianguyen/ifme#575]
Discovered while investigating #561, it's causing problems in IE10 because IE10 doesn't support the "const" keyword, and yet the minified application Javascript still has "const" in it. That means Babel is not configured correctly.

**Comment by HashNotAdam** [comment]
I don't believe this project uses Babel. Sprockets-es6 is brought in by foundation-rails but it isn't configured in ifme.

That is amazing, that `const` has been in `contributorReadMoreFeature` since 2016 😱 
That was never gonna work.

@julianguyen now might be a good time to start introducing ES6—thoughts?

**Comment by baohouse** [comment]
@nma Is adding ES6 support something that will be part of adding React to the project?

**Comment by baohouse** [comment]
@HashNotAdam Yep, you are right about this project not having babel configured; I assumed we had it because I saw babel configured, but it's actually part of the React work being done. I'll at least put in a PR to fix the 'const' in contributorReadMoreFeature.

**Comment by HashNotAdam** [comment]
Excited to hear it is coming soon; I've missed it over here.

**Comment by baohouse** [comment]
Closing this because it's now integrated via #579
