### ISSUE TITLE
Optimize asset sizes when loading homepage

### ISSUE THREAD

**Issue by baohouse** [julianguyen/ifme#604]
Loading everything on the homepage is a cool 5.9 MB.

- 4.4 MB of that are images, especially the contributor portraits
- 1019 KB are fonts (which can be optimized later by way of splitting up common unicode range from uncommon ranges into separate files)
- 478 KB is JavaScript (already served via gzip)

![screen shot 2017-09-06 at 7 44 19 pm](https://user-images.githubusercontent.com/4228012/30143785-77c57b84-933c-11e7-8f38-0befea6edd3c.png)

**Comment by julianguyen** [comment]
Thanks for bringing this up, there have been previous attempts to optimize the images:

https://github.com/julianguyen/ifme/issues/306
https://github.com/julianguyen/ifme/issues/411

Would be great to revisit this.

Also out of curiosity, I ran a performance audit in the Google dev console:

![image](https://user-images.githubusercontent.com/3010728/30144588-eacbe7a4-9340-11e7-8aec-2208535dba1c.png)
![image](https://user-images.githubusercontent.com/3010728/30144592-f77bd072-9340-11e7-8685-3f052dcfdf45.png)
etc.

**Comment by baohouse** [comment]
Ah, looks like Tracy's profile is still a PNG. The problem is that the contributors folder can be added to by anyone without knowing that the images are served up to the homepage directly. We probably should move these contributor photos into Cloudinary somehow.

**Comment by HashNotAdam** [comment]
Ha! Would you believe I have a branch for this? Let's team up 😄

**Comment by baohouse** [comment]
@HashNotAdam You're like a magician pulling rabbits out of hats 😆

**Comment by HashNotAdam** [comment]
#boredatwork

**Comment by HashNotAdam** [comment]
So, I think this is a higher priority than the items I looked at today, however, it also has "side effects" so I didn't want to submit anything without discussion.

The simplest solution would be to just resize the images to the maximum size that is required, save them all as JPEG, and optimise the file size. If we do this, we would need to update the documentation to help new contributors do this themselves but I think we can make it pretty painless. If we recommend people use tinyjpg.com, there would be a huge saving in file size without over-complicating the process. Without resizing, putting the existing images through that service would save ~3MB.

Another option would be to introduce something like ImageMagick and do live resizing on the server. This would mean that contributors don't need to know anything about how the files are used and, if dimensions change in the future, the originals can simply be adjusted. We could store the resized images in the tmp directory and test if they exist before resizing. This is extremely flexible but it adds another dependency (you need to install ImageMagick separate to Rails) and it uses a non-trivial amount of RAM while it is doing the transformation.

Instead of ImageMagick, but with the same benefits, there are also services like Cloudinary (already in this project) and we could look at uploading the file there. This could work pretty well if we generate a rake task that is run on deployment that syncs the images. While you don't get the fine-tuned optimisation that comes from manually managing the files, Cloudinary says they do optimise and it would give a pretty seamless solution for contributors. When I began writing this comment I thought I'd prefer the first option but, the more I looked into Cloudinary, the more I like this.

**Comment by baohouse** [comment]
First one is easy to do, but it requires people to be vigilant, and, well, humans are fallible.

The third option just had an integration matter I wasn't clear on, which was how do you sync the images; i.e. how do we know if an image has already been uploaded? And similarly, if a contributor changes her/his portrait, would this also update the corresponding image on Cloudinary? And how do we pull the proper links to the images when we render the contributor section? Is there a way to fetch the Cloudinary URL for a given image name? Do we store the URLs in the database?

**Comment by HashNotAdam** [comment]
There are a couple of ways we could manage it:
- just sync all images on deployment (there are 7,500 free transforms);
- for each file in the contributors' directory, test if there is a corresponding file on Cloudinary; or
- _if_ the deployment has an actual git clone and not just an export, we could do a diff between revisions (quick idea would be to use: `git diff --name-status $(git rev-parse HEAD~1) app/assets/images/contributors/`) and then remove, add, and update as needed.

**Comment by baohouse** [comment]
Reading the Cloudinary API, so looks like it's easy to reference the images by way of public id (which can be the filename, with a namespace prefix so we know it's coming from the contributors folder), which just requires two remaining things:
1. Generating the manifest of contributor image filenames as public ids (and then iterating over them and inserting [cl_image_tag](http://cloudinary.com/documentation/solution_overview) into the erb)
2. A way to upload the images to Cloudinary, per your suggestions (simple upload every deployment or git diff). I don't know much about the deployment process to have a say on this.

On point 1, it seems a bit much to have the server read the folder to generate the list every visit. It's probably more prudent to generate per deployment and cache the list.

**Comment by HashNotAdam** [comment]
100% this should be on deployment if we go this path. I haven't learnt a huge amount about Heroku and CircleCI in the last month so I'm comfortable it can be done, it's a question of picking a direction.
You think it's worth trying the Cloudinary option?
@julianguyen?

**Comment by baohouse** [comment]
#579 introduced an unoptimized webpack Javascript bundle that was 2.5MB. I've added Uglify to the webpack build via #616 and it dropped the filesize down to 760kb, however, there's still a remaining issue which is that webpack assets (JS and CSS) are served up without being gzip compressed.

**Comment by baohouse** [comment]
#635 Resolved the gzip of webpack assets.

**Comment by baohouse** [comment]
#641 is a temporary Cloudinary solution that should immediately reduce the image sizes on the homepage.

**Comment by baohouse** [comment]
#654 Reduced initial font footprint from 1020 kB down to 289 kB. The overall page footprint is now 1.2 MB. Where can we further shave?

- Optimize welcome_small.jpg file (and use CSS blur instead of welcome_small_blur.jpg).
- Figure out a way to lazy load JavaScript only as needed.
- Split up Lato font by language.
- Lazy load portraits only if the element is within view.

**Comment by julianguyen** [comment]
@baohouse I've been meaning to optimize welcome_small.jpg. I actually want redo the design of the footer and just use a solid colour instead, that way I can get rid of the font glow action going on lol.
